main: me.tazsjah.Init
author: Tazsjah
name: MiniVote
description: Voting system for minigames
version: 1.0
api-version: 1.19
commands:
  vote:
    description: Starts a new vote for x amount of time
  addvote:
    description: Adds a vote to the menu
  remvote:
    description: Removes a vote from the menu
  listvotes:
    description: List the possible votes